# Generated by Django 5.2.2 on 2025-06-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0002_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('DI', 'Директор'),
                                            ('AD', 'Администратор'),
                                            ('CO', 'Повар'),
                                            ('CA', 'Кассир'),
                                            ('CL', 'Уборщик')],
                                   default='CA', max_length=2),
        ),
    ]
